# 1. 字节交换
我们已经了解，存储在计算机内存中的数据取决于CPU使用的体系结构。它可能是小端的（重要性最低的存储在最小的地址），也可能是大端的（最重要的字节在最小的地址）。
### 1.1 numpy.ndarray.byteswap()
该函数在两种形式之间切换：大端和小端。

In [1]:
import numpy as np
a = np.array([1,256,8755],dtype=np.int16)

print 'Our array is:'
print a,'\n'

print 'Representation of data in memory in hexadecimal form:'
print map(hex,a)

# byteswap() function swaps in place by passing True parameter
print 'Applying byteswap() function:'
print a.byteswap(True)

print 'In hexadecimal form:'
print map(hex,a)
# We can see the bytes being swapped

Our array is:
[   1  256 8755] 

Representation of data in memory in hexadecimal form:
['0x1', '0x100', '0x2233']
Applying byteswap() function:
[  256     1 13090]
In hexadecimal form:
['0x100', '0x1', '0x3322']


# 2. 拷贝和视图
当执行函数时，一些会返回输入数组的拷贝，而另一些会返回视图。一方面当内容物理上存储在另外的位置，叫做Copy；而另一方面，只是提供了相同内存空间内容的不同视图，我们叫它View。

### 2.1 非拷贝
一些赋值操作没有做任何数组对象的拷贝。相反，只使用了原始数组的相同id()去访问它。id()函数返回Python对象的唯一标识符，与C语言中的指针类似。当然你也可以理解为C++或者Java中的引用(reference)。而且，任何一方的变化都会反映在另一方面。例如，一个变化的形状也会改变另一个的形状。举例如下：

In [3]:
a = np.arange(6)
print 'Our array is:'
print a,'\n'

print 'Applying id() func:'
print id(a),'\n'

print 'a is assigned to b:'
b = a
print b,'\n'

print 'b has same id():'
print id(b),'\n'

print 'Change shape of b:'
b.shape = 3,2
print b,'\n'

print 'Shape of a also gets changed:'
print a

Our array is:
[0 1 2 3 4 5] 

Applying id() func:
107853344 

a is assigned to b:
[0 1 2 3 4 5] 

b has same id():
107853344 

Change shape of b:
[[0 1]
 [2 3]
 [4 5]] 

Shape of a also gets changed:
[[0 1]
 [2 3]
 [4 5]]


### 2.2 视图/浅拷贝
NumPy有ndarray.view()方法，它是一个新的数组对象，它查看原始数组的相同数据。用谷歌搜到了numpy中view（视图）的[详细解释](http://scipy-cookbook.readthedocs.io/items/ViewsVsCopies.html#What-is-a-view-of-a-NumPy-array?)，大意是讲view()正如其名字所说，这只是查看数组数据的另一种方式，得到的数组对象与原始数组共享数据。换句话说，**两者之间的数据变化完全是一致的**。  
另外一点，对numpy中的数组进行**切片操作得到的也是视图**。  

In [8]:
a = np.arange(6).reshape(3,2)
print 'Array a:'
print a,'\n'

print 'Create view of a:'
b = a.view()
print b,'\n'

print 'id() for both the arrays are different:'
print 'id() of a:'
print id(a),'\n'
print 'id() of b:'
print id(b),'\n'

# Change the shape of b. It does not change the shape of a
b.shape = 2,3

print 'Shape of a:'
print a,'\n'

# the data in both objects are same all the time
print 'change the value of elements in b:'
b *= 2
print b,'\n'
print a

Array a:
[[0 1]
 [2 3]
 [4 5]] 

Create view of a:
[[0 1]
 [2 3]
 [4 5]] 

id() for both the arrays are different:
id() of a:
139517264 

id() of b:
139517184 

Shape of a:
[[0 1]
 [2 3]
 [4 5]] 

change the value of elements in b:
[[ 0  2  4]
 [ 6  8 10]] 

[[ 0  2]
 [ 4  6]
 [ 8 10]]


**注意：**视图/浅拷贝与2.1节当中的赋值操作（非拷贝）的差别就在于前者会创建新的对象，后者不会。两种方式都会导致当中的数据相互影响。如果需要改变原始的数组元素而拷贝的数据不变，这时就需要深拷贝。

### 2.3 深拷贝
函数ndarray.copy()创建了一个深拷贝。它是一个完整的数组以及其中的数据的拷贝，不与原始数组共享数据。

In [9]:
a = np.array([[10,10],[2,3],[4,5]])
print 'Array a is:'
print a,'\n'

print 'Create a deep copy of a:'
b = a.copy()
print 'Array b is:'
print b,'\n'

# b does not share any memory of a 
print 'Can we write b is a'
print b is a,'\n'

print 'Change the contents of b:'
b[0,0] = 100

print 'Modified array b:'
print b,'\n'

print 'a remains unchanged:'
print a

Array a is:
[[10 10]
 [ 2  3]
 [ 4  5]] 

Create a deep copy of a:
Array b is:
[[10 10]
 [ 2  3]
 [ 4  5]] 

Can we write b is a
False 

Change the contents of b:
Modified array b:
[[100  10]
 [  2   3]
 [  4   5]] 

a remains unchanged:
[[10 10]
 [ 2  3]
 [ 4  5]]
