# 索引

与python的内置容器对象一样，ndarray对象的内容可以通过**索引**和**切片**被访问和修改。之前提到，ndarray对象中的项遵循从零开始的索引，有三种索引方式可供选择：字段访问，基本切片以及高级索引。  
基本切片是python中N维切片基本概念的扩展。一个python切片对象由内置slice函数给定的start,stop和step参数构建而成，这个切片对象传递到numy数组中，用于提取数组的一部分。

### 1. 基本切片
基本切片是python中N维切片基本概念的扩展。一个python切片对象由内置slice函数给定的start,stop和step参数构建而成，这个切片对象传递到numy数组中，用于提取数组的一部分。

In [4]:
import numpy as np

a = np.arange(10)
s = slice(2,7,2)
print a[s]

[2 4 6]


上面的例子中，ndarray对象由arange()函数构建，同样的效果也可以通过由冒号分割的切片参数(start:stop:step)直接传递给ndarray对象实现。

In [8]:
# 切片索引开始，结束和步长全部给出
print a[2:7:2],'\n'

# 如果只有一个参数传入，与索引对应的元素项将被返回
print a[5],'\n'

# 从索引start=2开始切片
print a[2:]

[2 4 6] 

5 

[2 3 4 5 6 7 8 9]


上述操作对于多维ndarray也是一样。

In [12]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print a,'\n'

# 多维数组切片时，如果参数中没有逗号，则默认是按行进行切片
print a[1:],'\n' 

# 添加省略号和逗号，可以按列进行切分
print a[...,1:]

[[1 2 3]
 [3 4 5]
 [4 5 6]] 

[[3 4 5]
 [4 5 6]] 

[[2 3]
 [4 5]
 [5 6]]


### 2. 高级索引  
可以从ndarray中选择一个非元组序列，整数或者布尔类型的ndarray对象，或者至少有一个元素是一个序列对象的元组。高级索引通常返回的是数据的拷贝，与此相反，切片只呈现一个视图。  有两种类型的高级索引：整数和布尔。

#### 2.1 整数索引  
这种原理根据自身的N维索引帮助我们在数组中选择任意项。每个整数数组代表进入该维度的索引数量。当索引由与目标ndarray的维度相同数量的整数数组组成时，就变得简单明了。  
在以下示例中，选择了从ndarray对象的每一行中指定列的一个元素。因此，行索引包含所有行号，列索引指定要选择的元素。

In [15]:
x = np.array([[1,2],[3,4],[5,6]])
y = x[[0,1,2],[0,1,0]]
print x,'\n'
print y

[[1 2]
 [3 4]
 [5 6]] 

[1 4 5]


上面的例子相当于选择了ndarray中的(0,0),(1,1)和(2,0)位置的元素。  
下面的例子中，位于4x3数组四角的元素被选中。选择的行索引是[0,0]和[3,3]，而列索引是[0,2]和[0,2]。

In [18]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print x,'\n'

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
y = x[rows,cols]

# 输出结果是一个包含四角元素的ndarray对象
print y

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[ 0  2]
 [ 9 11]]


高级索引与基本索引可以通过使用切片(:)或者省略号与索引数组结合使用。下面的例子对行使用了切片，对列使用了高级索引，这与两者都使用切片的效果相同。但是高级索引引起的拷贝可能会导致不同的内存分布。

In [19]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])

print x,'\n'

# 切片
z = x[1:4,1:3]
print "切片之后，数组变为："
print z,'\n'

# 对数组的列使用高级索引
y = x[1:4,[1,2]]
print "对列使用高级索引："
print y

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

切片之后，数组变为：
[[ 4  5]
 [ 7  8]
 [10 11]] 

对列使用高级索引：
[[ 4  5]
 [ 7  8]
 [10 11]]


#### 2.2 布尔类型索引
当产生的对象是布尔运算的结果时，例如比较运算符，就使用这种高级索引。

In [30]:
print x,'\n'

# 可以看出对ndarray对象进行布尔运算时，实际操纵的是对象当中的每一个项
print x>5,'\n' 

print "打印大于5的元素项："
print x[x>5]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]] 

打印大于5的元素项：
[ 6  7  8  9 10 11]


遇到NaN元素时，可以使用~（辅助操作符）将其忽略。

In [22]:
a = np.array([np.nan,1,2,np.nan,3,4,5])
print a[~np.isnan(a)]

[ 1.  2.  3.  4.  5.]


也可以将非复数元素从数组中过滤掉。

In [25]:
a = np.array([1,2+6j,5,3.5+5j])
print a[np.iscomplex(a)]

[ 2.0+6.j  3.5+5.j]
