# 1. 广播特性
“广播”一词指的是numpy处理不同形状数组在算术运算时的能力。数组上的算术运算通常是对应的元素相计算，如果两个阵列的形状完全相同，则这些操作可以顺利进行。

In [1]:
import numpy as np

a =  np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
print c

[ 10  40  90 160]


因为numpy中广播特性的存在，它使不同类型的数组运算成为可能。较小的阵列广播到较大阵列的大小，以便它们具有兼容的形状。下面是适用于broadcasting特性的几种情况：
- 具有较小ndim的数组在其形状上预置有“1”。
- 输出形状的每个维度中的大小是该维度中输入大小的最大值。
- 输入可用于计算，如果其大小在特定维度上与输出大小匹配或其值恰好为1。
- 如果输入的维度大小为1，则该维度中的第一个数据条目将用于沿该维度的所有计算。

如果上述规则产生有效的结果并且下列之一成立，则称一组数据是可广播的：
- 数组的形状完全一样。 
- 数组具有相同的维度数量，每个维度的长度可以是常用长度或1。
- 具有太小尺寸的阵列可以将其形状预先设定为长度为1的尺寸，以使上述属性为真。

下面的程序展示了一个广播特性的例子：

In [5]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])

print a,'\n'
print b,'\n'
print a+b

[[  0.   0.   0.]
 [ 10.  10.  10.]
 [ 20.  20.  20.]
 [ 30.  30.  30.]] 

[ 1.  2.  3.] 

[[  1.   2.   3.]
 [ 11.  12.  13.]
 [ 21.  22.  23.]
 [ 31.  32.  33.]]


下面的图示解释了数组b是如何通过广播变为与a兼容的。
![broadcasting](https://www.tutorialspoint.com/numpy/images/array.jpg)

# 2. 迭代数组
Numpy库中包含一个迭代器对象np.nditer。这是一个高效的多维迭代器对象，使用它可以遍历数组。它使用python中的标准迭代器接口访问数组中的每一个元素。  
下面示例使用了np.arange()创建了一个3x4的数组，并且使用nditer对它进行迭代。

In [11]:
import numpy as np
a = np.arange(0,60,5).reshape(3,4)

print "原始数组是："
print a,'\n'

print "修改的数组是："
for x in np.nditer(a):
    print x,
print '\n'   

# 对数组转置的遍历结果也类似
b = a.T
print "原始数组的转置为："
print b,'\n'
print "修改的数组是："
for x in np.nditer(b):
    print x,

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]] 

修改的数组是：
0 5 10 15 20 25 30 35 40 45 50 55 

原始数组的转置为：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]] 

修改的数组是：
0 5 10 15 20 25 30 35 40 45 50 55


## 2.1 迭代顺序
如果使用F样式顺序存储相同的元素，则迭代器会选择更有效的迭代数组的方法。

In [14]:
print "原始数组："
print b,'\n'

print "以C样式顺序排序："
c = b.copy(order='C')
print c
for x in np.nditer(c):
    print x,
print '\n'

print "以F样式顺序排序："
c = b.copy(order='F')
print c
for x in np.nditer(c):
    print x,

原始数组：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]] 

以C样式顺序排序：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0 20 40 5 25 45 10 30 50 15 35 55 

以F样式顺序排序：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0 5 10 15 20 25 30 35 40 45 50 55


可以通过明确地提到nditer对象来使用特定的顺序。

In [15]:
print "原始数组："
print a,'\n'

print "以F样式顺序排序："
for x in np.nditer(a,order='F'):
    print x,
print '\n'

原始数组：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]] 

以F样式顺序排序：
0 20 40 5 25 45 10 30 50 15 35 55 



## 2.2 修改数组元素值
nditer对象有另一个可选参数：op_flags。它的默认值是read-only的，但是可以设置为read-write或者write-only模式。这将使用这个迭代器来修改数组元素。

In [17]:
print "原始数组："
print a,'\n'

for x in np.nditer(a,op_flags=['readwrite']):
    x[...] = 2 * x
print "修改的数组："
print a

原始数组：
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]] 

修改的数组：
[[  0  20  40  60]
 [ 80 100 120 140]
 [160 180 200 220]]


## 2.3 外部循环
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center;">Sr.No.</th>
<th style="text-align:center;">Parameter &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><p><b>c_index</b></p>
<p>C_order index can be racked</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><p><b>f_index</b></p>
<p>Fortran_order index is tracked</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><p><b>multi-index</b></p>
<p>Type of indexes with one per iteration can be tracked</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><p><b>external_loop</b></p>
<p>Causes values given to be one-dimensional arrays with multiple values instead of zero-dimensional array</p>
</td>
</tr>
</tbody></table>

在下面的例子中，迭代器遍历每列对应的一维数组。

In [18]:
print "原始数组："
print a,'\n'

print "修改的数组："
for x in np.nditer(a, flags = ['external_loop'], order = 'F'): 
   print x,

原始数组：
[[  0  20  40  60]
 [ 80 100 120 140]
 [160 180 200 220]] 

修改的数组：
[  0  80 160] [ 20 100 180] [ 40 120 200] [ 60 140 220]


## 2.4 广播迭代
如果两个数组是可广播的，一个组合的nditer对象可以同时迭代它们。假设一个数组a的维数为3X4，而另一个数组b的维数为1X4，则使用以下类型的迭代器（数组b被广播为a的大小）。

In [19]:
print "第一个数组："
print a,'\n'

print "第二个数组："
b = np.array([1,2,3,4],dtype=int)
print b,'\n'

print "修改的数组："
for x,y in np.nditer([a,b]):
    print "%d:%d" % (x,y),

第一个数组：
[[  0  20  40  60]
 [ 80 100 120 140]
 [160 180 200 220]] 

第二个数组：
[1 2 3 4] 

修改的数组：
0:1 20:2 40:3 60:4 80:1 100:2 120:3 140:4 160:1 180:2 200:3 220:4


# 3. 数组操作
Numpy包中有几个例程可用于处理ndarray对象中的元素。它们可以划分成以下几种类型：
## 3.1 改变形状
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;">Sr.No.</th>
<th style="text-align:center;">Shape &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><a href="/numpy/numpy_reshape.htm">reshape</a>
<p>Gives a new shape to an array without changing its data</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><a href="/numpy/numpy_ndarray_flat.htm">flat</a>
<p>A 1-D iterator over the array</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><a href="/numpy/numpy_ndarray_flatten.htm">flatten</a>
<p>Returns a copy of the array collapsed into one dimension</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><a href="/numpy/numpy_ndarray_ravel.htm">ravel</a>
<p>Returns a contiguous flattened array</p>
</td>
</tr>
</tbody></table>

**温馨提示：**要弄清楚np.flatten()和np.ravel()的区别：前者返回一份拷贝(copy)，所以对拷贝的修改不会影响原始数组内容；而后者返回的是视图(view)，对视图对象的修改会影响原始数组。但是只是元素值的变化，原始数组的形状不受影响。举例如下：

In [22]:
x = np.array([[1,2],[3,4]])
print "原始数组："
print x,'\n'


x.flatten()[1] = 100
print "对x的拷贝进行元素修改："
print x,'\n'

x.ravel()[1] = 100
print "对x的视图进行元素修改："
print x

原始数组：
[[1 2]
 [3 4]] 

对x的拷贝进行元素修改：
[[1 2]
 [3 4]] 

对x的视图进行元素修改：
[[  1 100]
 [  3   4]]


## 3.2 转置操作
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;">Sr.No.</th>
<th style="text-align:center;">Operation &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><a href="/numpy/numpy_transpose.htm">transpose</a>
<p>Permutes the dimensions of an array</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><a href="/numpy/numpy_ndarray_t.htm">ndarray.T</a>
<p>Same as self.transpose()</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><a href="/numpy/numpy_rollaxis.htm">rollaxis</a>
<p>Rolls the specified axis backwards</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><a href="/numpy/numpy_swapaxes.htm">swapaxes</a>
<p>Interchanges the two axes of an array</p>
</td>
</tr>
</tbody></table>

### rollaxis函数注解：
numpy.rollaxis(arr,axis,start=0)  
重新分配选择的``axis``到``start``位置上，start默认为0。

In [24]:
a = np.arange(24).reshape([2,3,4])

# 因为start = 0，所以rollaxis会把最后一个坐标轴axis= 2的数字4带到第一个位置。
b = np.rollaxis(a, 2)

print a.shape,'\n'
print b.shape

(2L, 3L, 4L) 

(4L, 2L, 3L)


与rollaxis类似，**swapaxes函数**形式如下：  
numpy.swapaxes(arr,axis1,axis2)  
此函数用于交换数组中的两个轴的值，这里不再举例说明。

## 3.3 改变维度
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;">Sr.No.</th>
<th style="text-align:center;">Dimension &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><a href="/numpy/numpy_broadcast.htm">broadcast</a>
<p>Produces an object that mimics broadcasting</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><a href="/numpy/numpy_broadcast_to.htm">broadcast_to</a>
<p>Broadcasts an array to a new shape</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><a href="/numpy/numpy_expand_dims.htm">expand_dims</a>
<p>Expands the shape of an array</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><a href="/numpy/numpy_squeeze.htm">squeeze</a>
<p>Removes single-dimensional entries from the shape of an array</p>
</td>
</tr>
</tbody></table>

## 3.4 数组联结
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;">Sr.No.</th>
<th style="text-align:center;">Array &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><a href="/numpy/numpy_concatenate.htm">concatenate</a>
<p>Joins a sequence of arrays along an existing axis</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><a href="/numpy/numpy_stack.htm">stack</a>
<p>Joins a sequence of arrays along a new axis</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><a href="/numpy/numpy_hstack.htm">hstack</a>
<p>Stacks arrays in sequence horizontally (column wise)</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><a href="/numpy/numpy_vstack.htm">vstack</a>
<p>Stacks arrays in sequence vertically (row wise)</p>
</td>
</tr>
</tbody></table>

## 3.5 数组分割
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;">Sr.No.</th>
<th style="text-align:center;">Array &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><a href="/numpy/numpy_split.htm">split</a>
<p>Splits an array into multiple sub-arrays</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><a href="/numpy/numpy_hsplit.htm">hsplit</a>
<p>Splits an array into multiple sub-arrays horizontally (column-wise)</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><a href="/numpy/numpy_vsplit.htm">vsplit</a>
<p>Splits an array into multiple sub-arrays vertically (row-wise)</p>
</td>
</tr>
</tbody></table>

## 3.6 添加/删除元素
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;">Sr.No.</th>
<th style="text-align:center;">Element &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><a href="/numpy/numpy_resize.htm">resize</a>
<p>Returns a new array with the specified shape</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><a href="/numpy/numpy_append.htm">append</a>
<p>Appends the values to the end of an array</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><a href="/numpy/numpy_insert.htm">insert</a>
<p>Inserts the values along the given axis before the given indices</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><a href="/numpy/numpy_delete.htm">delete</a>
<p>Returns a new array with sub-arrays along an axis deleted</p>
</td>
</tr>
<tr>
<td class="ts">5</td>
<td><a href="/numpy/numpy_unique.htm">unique</a>
<p>Finds the unique elements of an array</p>
</td>
</tr>
</tbody></table>